### ISSUE TITLE
Unable to generate project

### ISSUE THREAD

**Issue by nanorepublica** [knyghty/cookiecutter-django-package#1]
Hi Tom, 

I just tried this with the following inputs:

```
project_name [Django Foo]: Django cptemplate
project_description [A Django package that ...]: A management command to copy templates into your project
author [Tom Carrick]: Andrew Miller
email [tom@carrick.eu]: andrew@softwarecrafts.co.uk
github_username [knyghty]: softwarecrafts
```

and got the following error:

```py
Traceback (most recent call last):
  File "/Users/andrew/.pyenv/versions/3.8.1/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/Users/andrew/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cookiecutter/generate.py", line 179, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: "/Users/andrew/{{ cookiecutter.project_name.lower().replace(' ', '-') }}/tests/__init__.py"
```

The generated directory structure is as follows, once inside the root directory of the project:
```
$ tree
.
├── tests
└── {{ cookiecutter.project_name.lower().replace(' ', '_') }}

3 directories, 0 files
```

**Comment by nanorepublica** [comment]
This was my python/cookiecutter version
